parameters:
  internalFeedName: ''
  artifact: ''
  packages: ''
  vmImage: ''

jobs:
  - job: PublishArtifacts
    displayName: Publish artifacts
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - checkout: none

      - download: current
        artifact: ${{ parameters.artifact }}
        # quotes are needed since * can't be used as the first character without quotes
        patterns: "*/**/*.*upkg"

      - task: DotNetCoreCLI@2
        displayName: Publish CI package to Azure artifacts
        inputs:
          command: push
          nuGetFeedType: internal
          feedPublish: ${{ parameters.internalFeedName }}
          publishPackageMetadata: true
          packagesToPush: ${{ parameters.packages }}
