version: CI-Build-{build}
max_jobs: 1
branches:
  except:
    - gh-pages
    - docs
image: Visual Studio 2017
before_build:
  - nuget restore Telegram.Bot.sln
build:
  project: Telegram.Bot.sln
  publish_nuget: true
  verbosity: normal
after_build:
  - cmd: cd test/Telegram.Bot.Tests.Unit
  - cmd: dotnet test
test: off
nuget:
  disable_publish_on_pr: true
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/telegram-bot/api/v2/package
    api_key:
      secure: Dl2/cPfGdESLPBMd7Y+CIQomwOgNQ2+rUTylGGzMb0FaJaL4WgPPf5lzkY5KD4V6
    symbol_server: https://www.myget.org/F/telegram-bot/api/v2/package
    on:
      branch: develop
  - provider: NuGet
    api_key:
      secure: PQtvBUnIX09ERokw1/tZQb69s4pR7K1q08HM/26+D7sZCyQiW4+7+Kmrw6rXARw8
    on:
      branch: master

for:

-
  branches:
    only:
      - master

  configuration: Release

-
  branches:
    except:
      - master

  configuration: Debug
  build:
    publish_nuget_symbols: true
