language: csharp
dist: xenial
sudo: false
mono: none
dotnet: 2.2.203
branches:
  except:
  - master

# run interactive tests on the "develop" branch only
script: >
  cd "test/Telegram.Bot.Tests.Integ" &&
  dotnet test --configuration Release --list-tests &&
  dotnet test --configuration Release --no-build --logger trx --verbosity normal $([ "$TRAVIS_BRANCH" != 'develop' ] && echo '--filter "Category!=Interactive"')

notifications:
  email: false

## Notes:
### Limit concurrent jobs to only 1
### Disable building PRs (might expose env vars)

## Environment Variables:

# TelegramBot_ApiToken                      test-bot-api-token
# TelegramBot_AllowedUserNames              main_tester,some_other_user
# TelegramBot_SuperGroupChatId              -1234
# TelegramBot_ChannelChatId                 -9876
# TelegramBot_PaymentProviderToken          token-from-stripe-test-bot
# TelegramBot_TesterPrivateChatId           1234
# TelegramBot_StickerOwnerUserId            1234
# TelegramBot_RegularGroupMemberId          9876
