language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
branches:
  only:
  - develop
script:
  - cd "test/Telegram.Bot.Tests.Integ"
  - sh -c "dotnet test --configuration Release --list-tests"
  - sh -c "dotnet xunit -configuration Release -nobuild -stoponfail"
notifications:
  email: false

## Notes:
### Limit concurrent jobs to only 1
### Disable building PRs (might expose env vars)

## Environment Variables:

# TelegramBot_ApiToken                      test-bot-api-token
# TelegramBot_AllowedUserNames              main_tester,some_other_user
# TelegramBot_SuperGroupChatId              -1234
# TelegramBot_ChannelChatId                 -9876
# TelegramBot_PaymentProviderToken          token-from-stripe-test-bot
# TelegramBot_TesterPrivateChatId           1234
# TelegramBot_StickerOwnerUserId            1234
# TelegramBot_RegularGroupMemberId          9876
