language: csharp
solution: Telegram.Bot.sln

matrix:
  include:
    - os: linux
      dotnet: 1.0.0-preview2-003131
      env: DOTNETCORE=1
      mono: none
    - os: osx
      dotnet: 1.0.0-preview2-003121
      env: DOTNETCORE=1
      mono: none
    - os: linux
      mono: latest
    - os: osx
      mono: latest

script:
  - if [ -n "${DOTNETCORE}" ]; then time dotnet restore && dotnet pack; fi
  - if [ -z "${DOTNETCORE}" ]; then xbuild /p:Configuration=Release Telegram.Bot.sln; fi
