version: 9.0.0-{branch}-alpha{build}
branches:
  except:
    - gh-pages
os: Windows Server 2012
init:
  - git config --global core.autocrlf input
cache:
  - "C:\\Users\\appveyor\\.dnx\\packages -> **\\project.json"
install:
  - ps: dnvm upgrade -r clr
configuration: Debug
before_build:
  - ps: dnu restore
build:
  verbosity: normal
artifacts:
  - path: artifacts\bin\Telegram.Bot\Debug\*.nupkg