version: 9.0.0-ci.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
    - gh-pages
image: Visual Studio 2015
init:
  - git config --global core.autocrlf input
cache:
  - "C:\\Users\\appveyor\\.dnx\\packages -> **\\project.json"
install:
  - ps: dnvm upgrade -r clr
configuration: Debug
before_build:
  - ps: $projectJson = Get-ChildItem project.json -Recurse
  - ps: $json = ConvertFrom-Json (Get-Content $projectJson.FullName -Raw -Encoding UTF8)
  - ps: $json.version = $env:APPVEYOR_BUILD_VERSION
  - ps: Set-Content -Value (ConvertTo-Json $json -Depth 10) -Path $projectJson.FullName -Encoding UTF8
  - ps: dnu restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
after_build:
  - ps: "Get-ChildItem *.nupkg -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }"
test: off
deploy: off