version: 9.0.0-{branch}-alpha{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
    - gh-pages
image: Visual Studio 2015
init:
  - git config --global core.autocrlf input
cache:
  - "C:\\Users\\appveyor\\.dnx\\packages -> **\\project.json"
install:
  - ps: dnvm upgrade -r clr
configuration: Debug
before_build:
  - ps: dnu restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
after_build:
  - ps: "Get-ChildItem *.nupkg -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }"
test: off
deploy: off